# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [development, master]
  pull_request:
    branches:
      - "*"
  # paths:
  # - "**/src/**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version-file: [".nvmrc"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    # cancel any jobs that are currently running in favor of the latest one
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version-file: ${{ matrix.node-version-file }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Typescript check
        run: npm run ts:check
      - name: Lint check
        run: npm run lint
      - name: Style lint check
        run: npm run lint-styles
      - name: Unit Testing
        run: CI=true npm run test:ci
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          test-script: npm run test:ci
          coverage-file: report.json
